import { Router } from "express";
import { z } from "zod";
import type { DatabasePool } from "../database/pool.js";
import { requireRole, requireUser } from "../auth/middleware.js";
import type { AppConfig } from "../config.js";
import { generateQuizFromYouTube, isPublicYouTubeUrl } from "../ai/quiz.js";

const questionSchema = z.object({ id:z.uuid().optional(), question:z.string().min(1), options:z.array(z.string().min(1)).length(4), correctOption:z.number().int().min(0).max(3), explanation:z.string().optional().default("") });
const lessonSchema = z.object({ id:z.uuid().optional(), title:z.string().min(1), description:z.string().optional().default(""), durationMinutes:z.number().int().nonnegative().optional().default(0), videoType:z.enum(["YOUTUBE","DRIVE"]).optional().default("YOUTUBE"), videoUrl:z.string().optional().nullable(), driveFileId:z.string().optional().nullable(), attachmentName:z.string().optional().nullable(), attachmentDriveFileId:z.string().optional().nullable(), goals:z.string().optional().default(""), contents:z.string().optional().default(""), completionThreshold:z.number().int().min(1).max(100).optional().default(60), quiz:z.array(questionSchema).max(1).optional().default([]) });
const assignmentSchema = z.object({ type:z.enum(["ALL","ORGANIZATION","POSITION","USER"]), targetId:z.string().optional().nullable(), required:z.boolean().optional().default(false), dueDate:z.string().optional().nullable() });
const tagSchema=z.string().trim().min(1).max(40).transform((value)=>value.replace(/^#+/,""));
const courseSchema = z.object({ title:z.string().min(1), category:z.string().min(1), level:z.string().optional().default("레벨 1"), status:z.enum(["DRAFT","OPEN","CLOSED"]).optional().default("DRAFT"), description:z.string().optional().default(""), curriculumSummary:z.string().optional().default(""), thumbnail:z.string().optional().nullable(), startDate:z.string().optional().nullable(), endDate:z.string().optional().nullable(), surveyEnabled:z.boolean().optional().default(false), googleFormUrl:z.string().optional().nullable(), completionThreshold:z.number().int().min(1).max(100).optional().default(60), tags:z.array(tagSchema).max(12).optional().default([]), lessons:z.array(lessonSchema).optional().default([]), assignments:z.array(assignmentSchema).optional().default([]) }).superRefine((course,ctx)=>{
  if(course.status!=="OPEN")return;
  if(!course.lessons.length)ctx.addIssue({code:"custom",path:["lessons"],message:"운영 중인 과정에는 차시가 1개 이상 필요합니다."});
  course.lessons.forEach((lesson,index)=>{if(lesson.quiz.length!==1)ctx.addIssue({code:"custom",path:["lessons",index,"quiz"],message:"운영 중인 과정의 각 차시에는 퀴즈 1개가 필요합니다."});});
});

async function hydrate(pool:DatabasePool, course:any) {
  const lessons = await pool.query(`SELECT id,title,description,sequence,duration_minutes AS "durationMinutes",video_type AS "videoType",video_url AS "videoUrl",drive_file_id AS "driveFileId",attachment_name AS "attachmentName",attachment_drive_file_id AS "attachmentDriveFileId",goals,contents,completion_threshold AS "completionThreshold" FROM lessons WHERE course_id=$1 ORDER BY sequence`,[course.id]);
  for (const lesson of lessons.rows) lesson.quiz=(await pool.query(`SELECT id,question,options,correct_option AS "correctOption",explanation FROM quiz_questions WHERE lesson_id=$1 ORDER BY sequence`,[lesson.id])).rows;
  course.lessons=lessons.rows;
  course.assignments=(await pool.query(`SELECT id,assignment_type AS type,target_id AS "targetId",required,due_date AS "dueDate" FROM course_assignments WHERE course_id=$1`,[course.id])).rows;
  course.tags=(await pool.query(`SELECT tag FROM course_tags WHERE course_id=$1 ORDER BY tag`,[course.id])).rows.map((row:any)=>row.tag);
  return course;
}
async function resolveAssignmentUsers(client:any, assignment:any) {
  if (assignment.type==="ALL") return (await client.query(`SELECT id FROM users WHERE status='ACTIVE'`)).rows;
  if (assignment.type==="USER") return (await client.query(`SELECT id FROM users WHERE status='ACTIVE' AND (id::text=$1 OR employee_number=$1)`,[assignment.targetId])).rows;
  if (assignment.type==="POSITION") return (await client.query(`SELECT id FROM users WHERE status='ACTIVE' AND position=$1`,[assignment.targetId])).rows;
  return (await client.query(`SELECT u.id FROM users u JOIN organizations o ON o.id=u.organization_id WHERE u.status='ACTIVE' AND (o.id::text=$1 OR o.name=$1 OR o.path LIKE COALESCE((SELECT path||'%' FROM organizations WHERE id::text=$1 OR name=$1 LIMIT 1),'__NO_MATCH__'))`,[assignment.targetId])).rows;
}
async function replaceChildren(client:any, courseId:string, input:any, actor:string) {
  await client.query(`DELETE FROM course_tags WHERE course_id=$1`,[courseId]);
  for(const tag of [...new Set(input.tags)]) await client.query(`INSERT INTO course_tags(course_id,tag) VALUES($1,$2)`,[courseId,tag]);
  await client.query(`UPDATE lessons SET sequence=-sequence WHERE course_id=$1`,[courseId]);
  const keptLessonIds:string[]=[];
  for (let index=0;index<input.lessons.length;index++) {
    const lesson=input.lessons[index];
    let saved;
    if(lesson.id){saved=await client.query(`UPDATE lessons SET sequence=$3,title=$4,description=$5,duration_minutes=$6,video_type=$7,video_url=$8,drive_file_id=$9,attachment_name=$10,attachment_drive_file_id=$11,goals=$12,contents=$13,completion_threshold=$14,updated_at=now() WHERE id=$1 AND course_id=$2 RETURNING id`,[lesson.id,courseId,index+1,lesson.title,lesson.description,lesson.durationMinutes,lesson.videoType,lesson.videoUrl||null,lesson.driveFileId||null,lesson.attachmentName||null,lesson.attachmentDriveFileId||null,lesson.goals,lesson.contents,lesson.completionThreshold]);}
    if(!saved?.rowCount)saved=await client.query(`INSERT INTO lessons(course_id,sequence,title,description,duration_minutes,video_type,video_url,drive_file_id,attachment_name,attachment_drive_file_id,goals,contents,completion_threshold) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[courseId,index+1,lesson.title,lesson.description,lesson.durationMinutes,lesson.videoType,lesson.videoUrl||null,lesson.driveFileId||null,lesson.attachmentName||null,lesson.attachmentDriveFileId||null,lesson.goals,lesson.contents,lesson.completionThreshold]);
    const lessonId=saved.rows[0].id;keptLessonIds.push(lessonId);
    if(!lesson.quiz.length)await client.query(`DELETE FROM quiz_questions WHERE lesson_id=$1`,[lessonId]);
    else{const item=lesson.quiz[0];const existing=item.id?await client.query(`SELECT id FROM quiz_questions WHERE id=$1 AND lesson_id=$2`,[item.id,lessonId]):await client.query(`SELECT id FROM quiz_questions WHERE lesson_id=$1 ORDER BY sequence LIMIT 1`,[lessonId]);if(existing.rowCount)await client.query(`UPDATE quiz_questions SET sequence=1,question=$2,options=$3,correct_option=$4,explanation=$5 WHERE id=$1`,[existing.rows[0].id,item.question,JSON.stringify(item.options),item.correctOption,item.explanation]);else await client.query(`INSERT INTO quiz_questions(lesson_id,sequence,question,options,correct_option,explanation) VALUES($1,1,$2,$3,$4,$5)`,[lessonId,item.question,JSON.stringify(item.options),item.correctOption,item.explanation]);}
  }
  if(keptLessonIds.length)await client.query(`DELETE FROM lessons WHERE course_id=$1 AND NOT(id=ANY($2::uuid[]))`,[courseId,keptLessonIds]);else await client.query(`DELETE FROM lessons WHERE course_id=$1`,[courseId]);
  await client.query(`DELETE FROM course_assignments WHERE course_id=$1`,[courseId]);
  for(const assignment of input.assignments){
    const saved=await client.query(`INSERT INTO course_assignments(course_id,assignment_type,target_id,required,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[courseId,assignment.type,assignment.targetId||null,assignment.required,assignment.dueDate||null,actor]);
    const users=await resolveAssignmentUsers(client,assignment);
    const userIds=users.map((user:any)=>user.id);
    if(userIds.length)await client.query(`INSERT INTO enrollments(course_id,user_id,assignment_id,required,due_date) SELECT $1,selected_user.user_id,$3,$4,$5 FROM unnest($2::uuid[]) AS selected_user(user_id) ON CONFLICT(course_id,user_id) DO UPDATE SET required=enrollments.required OR EXCLUDED.required,due_date=COALESCE(EXCLUDED.due_date,enrollments.due_date),assignment_id=EXCLUDED.assignment_id,cancelled_at=NULL,status=CASE WHEN enrollments.status='CANCELLED' THEN 'ENROLLED' ELSE enrollments.status END`,[courseId,userIds,saved.rows[0].id,assignment.required,assignment.dueDate||null]);
  }
}
const selectCourse=`SELECT c.id,c.title,c.category,c.level,c.status,c.description,c.curriculum_summary AS "curriculumSummary",c.thumbnail,c.start_date AS "startDate",c.end_date AS "endDate",c.survey_enabled AS "surveyEnabled",c.google_form_url AS "googleFormUrl",c.completion_threshold AS "completionThreshold",c.created_at AS "createdAt",COUNT(DISTINCT e.id)::int AS learners,COALESCE(ROUND(100.0*COUNT(DISTINCT e.id) FILTER(WHERE e.status='COMPLETED')/NULLIF(COUNT(DISTINCT e.id),0)),0)::int AS rate FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id WHERE c.deleted_at IS NULL`;
export function createCoursesRouter(pool:DatabasePool,config:AppConfig){const router=Router();router.use(requireUser(pool));
 router.post("/ai/quiz",requireRole("ADMIN"),async(req,res)=>{const parsed=z.object({youtubeUrl:z.string().min(1),lessonTitle:z.string().max(200).optional()}).safeParse(req.body);if(!parsed.success||!isPublicYouTubeUrl(parsed.data.youtubeUrl))return res.status(400).json({data:null,error:{code:"INVALID_YOUTUBE_URL",message:"공개 YouTube 영상 주소를 입력해 주세요."}});if(!config.GEMINI_API_KEY)return res.status(503).json({data:null,error:{code:"GEMINI_NOT_CONFIGURED",message:"Gemini API 키가 설정되지 않았습니다."}});try{const quiz=await generateQuizFromYouTube({apiKey:config.GEMINI_API_KEY,youtubeUrl:parsed.data.youtubeUrl,lessonTitle:parsed.data.lessonTitle});res.json({data:quiz,error:null});}catch(error){console.error(JSON.stringify({level:"error",message:"gemini_quiz_generation_failed",error:error instanceof Error?error.message:String(error)}));const status=(error as any)?.status;res.status(status===400||status===404?422:502).json({data:null,error:{code:"GEMINI_GENERATION_FAILED",message:"영상을 분석하지 못했습니다. 공개 영상인지 확인한 뒤 다시 시도해 주세요."}});}});
 router.get("/tags/settings",requireRole("ADMIN"),async(_req,res,next)=>{try{const result=await pool.query(`SELECT tags.tag,COALESCE(featured.enabled,false) featured,featured.display_order AS "displayOrder",COUNT(tags.course_id)::int AS "courseCount" FROM course_tags tags LEFT JOIN featured_course_tags featured ON featured.tag=tags.tag GROUP BY tags.tag,featured.enabled,featured.display_order ORDER BY COALESCE(featured.display_order,9999),tags.tag`);res.json({data:result.rows,error:null});}catch(e){next(e);}});
 router.put("/tags/featured",requireRole("ADMIN"),async(req,res,next)=>{const parsed=z.object({tags:z.array(tagSchema).max(8)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR"}});const client=await pool.connect();try{await client.query("BEGIN");await client.query(`DELETE FROM featured_course_tags`);for(let index=0;index<parsed.data.tags.length;index++)await client.query(`INSERT INTO featured_course_tags(tag,display_order) VALUES($1,$2)`,[parsed.data.tags[index],index]);await client.query("COMMIT");res.json({data:parsed.data.tags,error:null});}catch(e){await client.query("ROLLBACK");next(e);}finally{client.release();}});
 router.get("/",async(req,res,next)=>{try{const result=await pool.query(`${selectCourse} GROUP BY c.id ORDER BY c.created_at DESC`);res.json({data:result.rows,error:null});}catch(e){next(e);}});
 router.get("/:id",async(req,res,next)=>{try{const result=await pool.query(`${selectCourse} AND c.id=$1 GROUP BY c.id`,[req.params.id]);if(!result.rowCount)return res.status(404).json({data:null,error:{code:"COURSE_NOT_FOUND"}});res.json({data:await hydrate(pool,result.rows[0]),error:null});}catch(e){next(e);}});
 router.post("/",requireRole("ADMIN"),async(req,res,next)=>{const parsed=courseSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR",details:parsed.error.flatten()}});const client=await pool.connect();try{await client.query("BEGIN");const x=parsed.data;const saved=await client.query(`INSERT INTO courses(title,category,level,status,description,curriculum_summary,thumbnail,start_date,end_date,survey_enabled,google_form_url,completion_threshold,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[x.title,x.category,x.level,x.status,x.description,x.curriculumSummary,x.thumbnail,x.startDate,x.endDate,x.surveyEnabled,x.googleFormUrl,x.completionThreshold,req.currentUser!.id]);await replaceChildren(client,saved.rows[0].id,x,req.currentUser!.id);await client.query("COMMIT");res.status(201).json({data:await hydrate(pool,saved.rows[0]),error:null});}catch(e){await client.query("ROLLBACK");next(e);}finally{client.release();}});
 router.put("/:id",requireRole("ADMIN"),async(req,res,next)=>{const parsed=courseSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR",details:parsed.error.flatten()}});const client=await pool.connect();try{await client.query("BEGIN");const x=parsed.data,courseId=String(req.params.id);const saved=await client.query(`UPDATE courses SET title=$2,category=$3,level=$4,status=$5,description=$6,curriculum_summary=$7,thumbnail=$8,start_date=$9,end_date=$10,survey_enabled=$11,google_form_url=$12,completion_threshold=$13,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING *`,[courseId,x.title,x.category,x.level,x.status,x.description,x.curriculumSummary,x.thumbnail,x.startDate,x.endDate,x.surveyEnabled,x.googleFormUrl,x.completionThreshold]);if(!saved.rowCount){await client.query("ROLLBACK");return res.status(404).json({data:null,error:{code:"COURSE_NOT_FOUND"}});}await replaceChildren(client,courseId,x,req.currentUser!.id);await client.query("COMMIT");res.json({data:await hydrate(pool,saved.rows[0]),error:null});}catch(e){await client.query("ROLLBACK");next(e);}finally{client.release();}});
 router.delete("/:id",requireRole("ADMIN"),async(req,res,next)=>{try{const result=await pool.query(`UPDATE courses SET deleted_at=now(),status='CLOSED' WHERE id=$1 AND deleted_at IS NULL`,[req.params.id]);if(!result.rowCount)return res.status(404).json({data:null,error:{code:"COURSE_NOT_FOUND"}});res.status(204).end();}catch(e){next(e);}});return router;}
